loevgaard_sylius_brand_admin_ajax:
    resource: "@LoevgaardSyliusBrandPlugin/Resources/config/routing/admin/ajax.yaml"
    prefix: /ajax

loevgaard_sylius_brand_admin_brand:
    resource: |
        alias: loevgaard_sylius_brand.brand
        section: admin
        templates: '@SyliusAdmin/Crud'
        redirect: update
        grid: loevgaard_sylius_brand_admin_brand
        vars:
            all:
                subheader: loevgaard_sylius_brand.ui.brand
                templates:
                    form: "@LoevgaardSyliusBrandPlugin/Admin/Brand/_form.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
